name: Build
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'
    - name: Fix missing entries
      run: 'go get -t .'
    - name: Build application
      run: 'go build -tags=nomsgpack -ldflags="-s -w" -o bearpush ./cmd/bearpush/'
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: Executables (${{ matrix.arch }})
        path: "${{ github.workspace }}/bearpush"
        if-no-files-found: error
